branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test (3.8)"
          - "test (3.9)"
          - "test (3.10)"
          - "test (3.11)"
          - "test (3.12)"
          - "PR Author Review"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null