name: Owner PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-owner:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      is-owner: ${{ steps.check-owner.outputs.is_owner }}

    steps:
    - name: Check if PR is from owner
      id: check-owner
      run: |
        if [ "${{ github.event.pull_request.user.login }}" == "${{ github.repository_owner }}" ]; then
          echo "is_owner=true" >> $GITHUB_OUTPUT
        else
          echo "is_owner=false" >> $GITHUB_OUTPUT
        fi

  owner-pr:
    needs: check-owner
    runs-on: ubuntu-latest
    if: needs.check-owner.outputs.is-owner == 'true'
    steps:
      - name: Owner PR - Auto Approve
        run: echo "PR is from the repository owner - automatically approved"

  external-pr:
    needs: check-owner
    runs-on: ubuntu-latest
    if: needs.check-owner.outputs.is-owner == 'false'
    steps:
      - name: Wait for review
        run: |
          echo "PR is from an external contributor"
          echo "Waiting for repository owner review"
          exit 1  # Fail the check to prevent merging without review