name: Owner PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-owner:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR is from owner
      id: is-owner
      run: |
        if [ "${{ github.event.pull_request.user.login }}" == "${{ github.repository_owner }}" ]; then
          echo "Result=success" >> $GITHUB_OUTPUT
        else
          echo "Result=needs-review" >> $GITHUB_OUTPUT
        fi

    - name: Set status for owner
      if: steps.is-owner.outputs.Result == 'success'
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'PR Author Review'
        state: 'success'
        sha: ${{ github.event.pull_request.head.sha }}

    - name: Set status for external contributor
      if: steps.is-owner.outputs.Result == 'needs-review'
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'PR Author Review'
        state: 'pending'
        description: 'PR requires review from repository owner'
        sha: ${{ github.event.pull_request.head.sha }}